### ISSUE TITLE
Where to find holding registers?

### ISSUE THREAD

**Issue by gitisz** [fronczek/apc_modbus#1]
Hello!  I found this repo from an issue on network UPS tools.  Question:  how/where did you get the codes for your lookups?  Example:

```
c.read_holding_registers(151, 1)
```

In the example above, how did you learn 151 returns input voltage?

Thanks!

**Comment by fronczek** [comment]
Hi, Please check this official docs: https://www.se.com/us/en/download/document/SPD_MPAO-98KJ7F_EN/ and https://www.se.com/us/en/download/document/SPD_LFLG-A32G3L_EN/

**Comment by gitisz** [comment]
That's exactly what I needed, thank you!
