### ISSUE TITLE
Installation instructions (for noobs including)

### ISSUE THREAD

**Issue by man55** [fronczek/apc_modbus#2]
Hello!
Can someone write step by step instructions on how to install and use this script?
After reading the README.md is still not clear to me.
In particular, I'm interested on installing for NUT on raspberry pi.
Many thanks in advance!

**Comment by fronczek** [comment]
Hey,
I'm not good at creatig docs ;-)
The procedure is:
1. Connect ethernet cable to the UPS "cloud" port (usually marked in green)
2. Enable and configure Modbus TCP support on the UPS (using UPS menu with physical buttons): UPS should get IP address and start listening on TCP 502 port. Your model needs to have ethernet port and support modbus obviously.
3. Try to test the python script manually - you should get some meaningful output now, like below. Remember to set proper (our) IP port and ID inside the script or use command line arguments.
```
user@host:/opt$ sudo -u Debian-snmp /opt/apc_modbus2snmp.py -v
TEST MODE
ups_AdvIdentSerialNumber is <class 'str'> and is equal to: 123456
ups_AdvIdentSkuNumber is <class 'str'> and is equal to: SMT1500IC
ups_AdvTestDiagnosticsResults is <class 'int'> and is equal to: 1
ups_ApparentPowerPct is <class 'float'> and is equal to: 10.21875
ups_BasicIdentModel is <class 'str'> and is equal to: Smart-UPS 1500
ups_BasicIdentName is <class 'str'> and is equal to: APC UPS
ups_BasicOutputStatus is <class 'int'> and is equal to: 2
ups_BasicStateOutputState is <class 'str'> and is equal to: 0001010000000000001000000000000000000000000000000000000000000000
ups_BattChargePct is <class 'float'> and is equal to: 100.0
ups_BattRuntimeLeft is <class 'int'> and is equal to: 8506
ups_BattTemp is <class 'float'> and is equal to: 31.3125
```
4. Install snmp daemon, add the `pass` line from README.md, configure access rights, communities, etc and restart snmpd service.
5. Now your machine is emulating/pretending APC UPS via SNMP. Each time your machine gets SNMP query it will run the python script and export the output as SNMP OIDs.
```
user@host:/opt$ snmpwalk -v2c -c public localhost .1.3.6.1.4.1.318.1.1.1.2.2.2.0
iso.3.6.1.4.1.318.1.1.1.2.2.2.0 = Gauge32: 31
user@host:/opt$ snmpwalk -v2c -c public localhost .1.3.6.1.4.1.318.1.1.1.2.2.3.0
iso.3.6.1.4.1.318.1.1.1.2.2.3.0 = Timeticks: (859000) 2:23:10.00
```
6. Now you can configure any device or software supporting SNMP UPS to run (Synology or Qnap NAS, PRTG, NUT, etc)

Keep in mid this project is written just-for-fun. It should not be meant as "production" ;-)
